### ISSUE TITLE
Handle failures to talk to Tessa more elegantly

### ISSUE THREAD

**Issue by tpett** [watermarkchurch/tessa#16]
At the moment a failure to talk to Tessa will result in the page not even loading.

**Comment by tpett** [comment]
It would be better if it showed an error message in the dropzone box.

**Comment by jpowell** [comment]
The problem exists not only in the form but anywhere an asset is referenced. After having some time to wrap my head around this issue and get familiar with the code, it seems like we want to more than silence service failures. Some cases I can think of:
- asset has been uploaded, but service is unavailable - we'd probably want to display to the user that something is there, but can't be retrieved
- asset has not been uploaded and service is unavailable - fail silently, render as if service is up
- asset exists in client DB, but not in Tessa service DB - act as if no asset exists and allow to be overwritten?

**Comment by jpowell** [comment]
If we do go the route of returning something like `Tessa::AssetUnavailable`, then we may want to add some view helpers to the gem that can abstract out logic checking.
